# .github/workflows/your-workflow.yml

name: Deploy Application

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Node.js environment
      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'  # Specify your Node.js version

      # 3. Install Dependencies
      - name: Install Dependencies
        run: npm install

      # 4. Build the Application (if applicable)
      - name: Build Application
        run: npm run build

      # 5. Deploy the Application
      - name: Deploy Application
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Inject the secret as an environment variable
        run: npm run deploy  # Replace with your actual deploy command
